In [1]:
import polars as pl
import os
import glob
from tqdm import tqdm

## Functions

In [2]:
def reorder_cols(df: pl.DataFrame) -> pl.DataFrame:
	"""
	Reorders the columns of a DataFrame so that 'sample' is the first column if it exists.
	"""
	cols = df.columns

	if "sample" in cols:
		cols.remove("sample")
		cols.insert(0, "sample")

	return df[cols]

In [3]:
def snv_filter(df: pl.DataFrame):
    return df.filter(
        (pl.col("ref").str.len_chars() == 1) &
        (pl.col("alt").str.len_chars() == 1)
	)

In [4]:
def summarize_res(df: pl.DataFrame) -> pl.DataFrame:
	
	bool_cols = df['filter_1_mutation_intra_hairpin_loop':'filter_8_low_quality'].columns
	str_cols = df['msec_filter_123':'msec_filter_all'].columns
	n_variants = df.height

	# Initialize a dictionary
	results = {
		"filter": [],
		"percentage": [],
		"n_failed": []
	}

	# Populate the dictionary inside the loops
	for col in bool_cols:
		n_failed = df[col].sum() # Sum counts True values
		
		results["filter"].append(col)
		results["percentage"].append((n_failed / n_variants) * 100)
		results["n_failed"].append(n_failed)

	for col in str_cols:
		n_failed = df.filter(~pl.col(col).is_null()).height # Count non-nulls
		
		results["filter"].append(col)
		results["percentage"].append((n_failed / n_variants) * 100)
		results["n_failed"].append(n_failed)

	# Create DataFrame from the dictionary
	return pl.DataFrame(results).with_columns(pl.lit(n_variants).alias("total_variants"))

### MicroSEC filter Description

The MicroSEC pipeline contains 8 filtering processes.  

- Filter 1  : Shorter-supporting lengths distribute too short to occur (1-1 and 1-2).  
	- Filter 1-1: P-values are less than the threshold_p(default: 10^(-6)).  
	- Filter 1-2: The shorter-supporting lengths distributed over less than 75% of the read length.  
- Filter 2  : Hairpin-structure induced error detection (2-1 and 2-2).  
	- Filter 2-1: Palindromic sequences exist within 200 bases.  
	- Filter 2-2: >=50% mutation-supporting reads contains a reverse complementary sequence of the opposite strand consisting >= 15 bases.  
- Filter 3  : 3'-/5'-supporting lengths are too densely distributed to occur (3-1 and 3-2).  
	- Filter 3-1: P-values are less than the threshold_p(default: 10^(-6)).  
	- Filter 3-2: The distributions of 3'-/5'-supporting lengths are within 75% of the read length.  
- Filter 4  : >=15% mutations were called by chimeric reads comprising two distant regions.  
- Filter 5  : >=50% mutations were called by soft-clipped reads.  
- Filter 6  : Mutations locating at simple repeat sequences.  
- Filter 7  : Indel mutations locating at a >=15 homopolymer.  
- Filter 8  : >=10% of bases are low quality (Quality score <18) in the mutation supporting reads.  

Filter 1, 2, 3, and 4 detect possible FFPE artifacts.  
Filter 5 may also be FFPE artifacts or mapping errors.  
Filter 6, 7, and 8 detect frequent errors caused by the next generation sequencing platform.  
Supporting lengths are adjusted considering small repeat sequences around the mutations.  
  
Results are saved in a tsv file.  

github url: https://github.com/MANO-B/MicroSEC

## Main
### VCF

In [5]:
msec_paths = sorted(glob.glob("../vcf-micr-svf/*/*.microsec.tsv"))

all_res = []

for path in tqdm(msec_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t", infer_schema_length = 1000).rename(lambda x : x.lower())
	
	all_res.append(df)
	
vcf_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

100%|██████████| 1641/1641 [02:14<00:00, 12.21it/s]

In [6]:
vcf_df

shape: (46_352, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-100115 ┆ 12-del   ┆ chr1  ┆ 11190697  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr1  ┆ 16262742  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr1  ┆ 45797760  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr10 ┆ 43601830  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr11 ┆ 118307334 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-213329 ┆ 1-snv    ┆ chr17 ┆ 37856504  ┆ … ┆ null       ┆ null       ┆ null       ┆ filter 1: │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213329 ┆ 1-snv    ┆ chr22 ┆ 29108003  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr4  ┆ 1920021   ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr7  ┆ 55268044  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chrX  ┆ 66765516  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [7]:
## Samples that could be processed
vcf_df["sample"].unique()

shape: (1_641,)
Series: 'sample' [str]
[
	"ORD-1616957-01"
	"ORD-1977243-01"
	"ORD-1407403-01"
	"ORD-2099386-01"
	"ORD-1593214-01"
	…
	"ORD-2016906-01"
	"ORD-2093178-01"
	"ORD-1721357-01"
	"ORD-2006244-01"
	"ORD-1218428-01"
]

In [8]:
# All Filters
vcf_arti_all_filter = vcf_df.filter(~pl.col("msec_filter_all").is_null()).pipe(snv_filter)
display(vcf_arti_all_filter)
# Number of Samples with >= 1 artifacts
vcf_arti_all_filter["sample"].n_unique()

shape: (1_712, 37)
┌─────────────┬──────────┬───────┬───────────┬───┬─────────────┬────────────┬────────────┬─────────┐
│ sample      ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filter ┆ msec_filte ┆ msec_filte ┆ comment │
│ ---         ┆ ---      ┆ ---   ┆ ---       ┆   ┆ _123        ┆ r_1234     ┆ r_all      ┆ ---     │
│ str         ┆ str      ┆ str   ┆ i64       ┆   ┆ ---         ┆ ---        ┆ ---        ┆ str     │
│             ┆          ┆       ┆           ┆   ┆ str         ┆ str        ┆ str        ┆         │
╞═════════════╪══════════╪═══════╪═══════════╪═══╪═════════════╪════════════╪════════════╪═════════╡
│ ORD-1048486 ┆ 1-snv    ┆ chr4  ┆ 55140704  ┆ … ┆ Artifact    ┆ Artifact   ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆ suspicious  ┆ suspicious ┆ suspicious ┆         │
│ ORD-1049250 ┆ 1-snv    ┆ chr11 ┆ 69518363  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-1050682 ┆ 1-snv    ┆ chr19 ┆ 11098593  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-1050682 ┆ 1-snv    ┆ chr5  ┆ 79950719  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-1075235 ┆ 1-snv    ┆ chr11 ┆ 118369282 ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ …           ┆ …        ┆ …     ┆ …         ┆ … ┆ …           ┆ …          ┆ …          ┆ …       │
│ ORD-2130093 ┆ 1-snv    ┆ chrX  ┆ 63411335  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-2130099 ┆ 1-snv    ┆ chrX  ┆ 63411410  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-2131606 ┆ 1-snv    ┆ chr13 ┆ 48954189  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-2131606 ┆ 1-snv    ┆ chr17 ┆ 29483000  ┆ … ┆ null        ┆ null       ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆             ┆            ┆ suspicious ┆         │
│ ORD-2133291 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact    ┆ Artifact   ┆ Artifact   ┆ null    │
│ -01         ┆          ┆       ┆           ┆   ┆ suspicious  ┆ suspicious ┆ suspicious ┆         │
└─────────────┴──────────┴───────┴───────────┴───┴─────────────┴────────────┴────────────┴─────────┘

919

In [9]:
# Filter 1234
vcf_arti_filter_1234 = vcf_df.filter(~pl.col("msec_filter_1234").is_null()).pipe(snv_filter)
display(vcf_arti_filter_1234)
# Number of Samples with >= 1 artifacts
vcf_arti_filter_1234["sample"].n_unique()

shape: (669, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-104848 ┆ 1-snv    ┆ chr4  ┆ 55140704  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-108442 ┆ 1-snv    ┆ chr22 ┆ 29689746  ┆ … ┆ null       ┆ Artifact   ┆ Artifact   ┆ null      │
│ 3-01       ┆          ┆       ┆           ┆   ┆            ┆ suspicious ┆ suspicious ┆           │
│ ORD-108739 ┆ 1-snv    ┆ chr2  ┆ 47643016  ┆ … ┆ null       ┆ Artifact   ┆ Artifact   ┆ null      │
│ 2-01       ┆          ┆       ┆           ┆   ┆            ┆ suspicious ┆ suspicious ┆           │
│ ORD-111186 ┆ 1-snv    ┆ chr11 ┆ 118354217 ┆ … ┆ null       ┆ Artifact   ┆ Artifact   ┆ null      │
│ 4-01       ┆          ┆       ┆           ┆   ┆            ┆ suspicious ┆ suspicious ┆           │
│ ORD-111406 ┆ 1-snv    ┆ chr2  ┆ 212288966 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 3-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-211504 ┆ 1-snv    ┆ chr16 ┆ 3778242   ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-211504 ┆ 1-snv    ┆ chrX  ┆ 63411333  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-211780 ┆ 1-snv    ┆ chr3  ┆ 178952085 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 8-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-211884 ┆ 1-snv    ┆ chr2  ┆ 25463568  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 2-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213329 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

410

In [10]:
summarize_res(vcf_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 0.914739   ┆ 424      ┆ 46352          │
│ filter_2_hairpin_structure      ┆ 0.030204   ┆ 14       ┆ 46352          │
│ filter_3_microhomology_induced… ┆ 1.382896   ┆ 641      ┆ 46352          │
│ filter_4_highly_homologous_reg… ┆ 1.279341   ┆ 593      ┆ 46352          │
│ filter_5_soft_clipped_reads     ┆ 0.509147   ┆ 236      ┆ 46352          │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 2.524163   ┆ 1170     ┆ 46352          │
│ filter_8_low_quality            ┆ 3.21669    ┆ 1491     ┆ 46352          │
│ msec_filter_123                 ┆ 1.876942   ┆ 870      ┆ 46352          │
│ msec_filter_1234                ┆ 3.121764   ┆ 1447     ┆ 46352          │
│ msec_filter_all                 ┆ 10.433207  ┆ 4836     ┆ 46352          │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [11]:
summarize_res(vcf_arti_filter_1234)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 20.478326  ┆ 137      ┆ 669            │
│ filter_2_hairpin_structure      ┆ 0.149477   ┆ 1        ┆ 669            │
│ filter_3_microhomology_induced… ┆ 30.044843  ┆ 201      ┆ 669            │
│ filter_4_highly_homologous_reg… ┆ 62.481315  ┆ 418      ┆ 669            │
│ filter_5_soft_clipped_reads     ┆ 5.082212   ┆ 34       ┆ 669            │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.44843    ┆ 3        ┆ 669            │
│ filter_8_low_quality            ┆ 7.473842   ┆ 50       ┆ 669            │
│ msec_filter_123                 ┆ 37.967115  ┆ 254      ┆ 669            │
│ msec_filter_1234                ┆ 100.0      ┆ 669      ┆ 669            │
│ msec_filter_all                 ┆ 100.0      ┆ 669      ┆ 669            │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [12]:
summarize_res(vcf_arti_all_filter)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 8.002336   ┆ 137      ┆ 1712           │
│ filter_2_hairpin_structure      ┆ 0.058411   ┆ 1        ┆ 1712           │
│ filter_3_microhomology_induced… ┆ 11.740654  ┆ 201      ┆ 1712           │
│ filter_4_highly_homologous_reg… ┆ 24.415888  ┆ 418      ┆ 1712           │
│ filter_5_soft_clipped_reads     ┆ 8.703271   ┆ 149      ┆ 1712           │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 3.621495   ┆ 62       ┆ 1712           │
│ filter_8_low_quality            ┆ 35.046729  ┆ 600      ┆ 1712           │
│ msec_filter_123                 ┆ 14.836449  ┆ 254      ┆ 1712           │
│ msec_filter_1234                ┆ 39.077103  ┆ 669      ┆ 1712           │
│ msec_filter_all                 ┆ 100.0      ┆ 1712     ┆ 1712           │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

### XML

In [13]:
msec_xml_paths = sorted(glob.glob("../xml-micr-svf/*/*.microsec.tsv"))
len(msec_xml_paths)

1606

In [14]:
all_res = []

for path in tqdm(msec_xml_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t", infer_schema_length = 1000).rename(lambda x: x.lower())
	
	all_res.append(df)
	
xml_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

100%|██████████| 1606/1606 [01:12<00:00, 22.24it/s]

In [15]:
xml_df

shape: (21_599, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-100115 ┆ chr1  ┆ 11190697  ┆ CGTGGTGGCG ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 9-01       ┆       ┆           ┆ GCA        ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-100115 ┆ chr1  ┆ 16262742  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr1  ┆ 45797760  ┆ T          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr10 ┆ 43601830  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr11 ┆ 118307334 ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-213329 ┆ chr17 ┆ 37856504  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ filter 1: │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213329 ┆ chr22 ┆ 29108003  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chr4  ┆ 1920021   ┆ A          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chr7  ┆ 55268044  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chrX  ┆ 66765516  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
## Samples that could be processed
xml_df["sample"].unique()

shape: (1_606,)
Series: 'sample' [str]
[
	"ORD-1974403-01"
	"ORD-1888385-01"
	"ORD-1246850-01"
	"ORD-1884020-01"
	"ORD-1939379-01"
	…
	"ORD-1094680-01"
	"ORD-1462572-01"
	"ORD-1504082-01"
	"ORD-2021785-01"
	"ORD-1817689-01"
]

In [17]:
# All artifacts
xml_arti_all_filter = xml_df.filter(~pl.col("msec_filter_all").is_null()).pipe(snv_filter)
display(xml_arti_all_filter)
# Number of Samples with >= 1 artifacts
xml_arti_all_filter["sample"].n_unique()

shape: (844, 47)
┌──────────────┬───────┬───────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────┐
│ sample       ┆ chrom ┆ pos       ┆ ref ┆ … ┆ msec_filter_ ┆ msec_filter_ ┆ msec_filter ┆ comment │
│ ---          ┆ ---   ┆ ---       ┆ --- ┆   ┆ 123          ┆ 1234         ┆ _all        ┆ ---     │
│ str          ┆ str   ┆ i64       ┆ str ┆   ┆ ---          ┆ ---          ┆ ---         ┆ str     │
│              ┆       ┆           ┆     ┆   ┆ str          ┆ str          ┆ str         ┆         │
╞══════════════╪═══════╪═══════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════╡
│ ORD-1048486- ┆ chr4  ┆ 55140704  ┆ G   ┆ … ┆ Artifact     ┆ Artifact     ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆ suspicious   ┆ suspicious   ┆ suspicious  ┆         │
│ ORD-1050682- ┆ chr19 ┆ 11098593  ┆ G   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-1050682- ┆ chr5  ┆ 79950719  ┆ C   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-1075235- ┆ chr9  ┆ 98278972  ┆ T   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-1094680- ┆ chr19 ┆ 15376352  ┆ G   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ …            ┆ …     ┆ …         ┆ …   ┆ … ┆ …            ┆ …            ┆ …           ┆ …       │
│ ORD-2130093- ┆ chrX  ┆ 63411335  ┆ C   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-2130099- ┆ chrX  ┆ 63411410  ┆ C   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-2131606- ┆ chr13 ┆ 48954189  ┆ G   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-2131606- ┆ chr17 ┆ 29483000  ┆ G   ┆ … ┆ null         ┆ null         ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆              ┆              ┆ suspicious  ┆         │
│ ORD-2133291- ┆ chr11 ┆ 118343321 ┆ A   ┆ … ┆ Artifact     ┆ Artifact     ┆ Artifact    ┆ null    │
│ 01           ┆       ┆           ┆     ┆   ┆ suspicious   ┆ suspicious   ┆ suspicious  ┆         │
└──────────────┴───────┴───────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────┘

574

In [18]:
# Filter 1234
xml_arti_filter_1234 = xml_df.filter(~pl.col("msec_filter_1234").is_null()).pipe(snv_filter)
display(xml_arti_filter_1234)
# Number of Samples with >= 1 artifacts
xml_arti_filter_1234["sample"].n_unique()

shape: (161, 47)
┌─────────────┬───────┬───────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ sample      ┆ chrom ┆ pos       ┆ ref ┆ … ┆ msec_filter ┆ msec_filter ┆ msec_filter ┆ comment    │
│ ---         ┆ ---   ┆ ---       ┆ --- ┆   ┆ _123        ┆ _1234       ┆ _all        ┆ ---        │
│ str         ┆ str   ┆ i64       ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str        │
│             ┆       ┆           ┆     ┆   ┆ str         ┆ str         ┆ str         ┆            │
╞═════════════╪═══════╪═══════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ ORD-1048486 ┆ chr4  ┆ 55140704  ┆ G   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-1114063 ┆ chr2  ┆ 212288966 ┆ C   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-1151545 ┆ chr22 ┆ 29090061  ┆ G   ┆ … ┆ null        ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-1219316 ┆ chr16 ┆ 396589    ┆ C   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-1245811 ┆ chr8  ┆ 117878929 ┆ G   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ …           ┆ …     ┆ …         ┆ …   ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ ORD-2115040 ┆ chr16 ┆ 3778242   ┆ C   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-2115040 ┆ chrX  ┆ 63411333  ┆ C   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-2117808 ┆ chr3  ┆ 178952085 ┆ A   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
│ ORD-2118842 ┆ chr2  ┆ 25463568  ┆ A   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ filter 1:  │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆ p is       │
│             ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆ small, but │
│             ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆ sup…       │
│ ORD-2133291 ┆ chr11 ┆ 118343321 ┆ A   ┆ … ┆ Artifact    ┆ Artifact    ┆ Artifact    ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆ suspicious  ┆ suspicious  ┆ suspicious  ┆            │
└─────────────┴───────┴───────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

136

In [19]:
summarize_res(xml_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 0.763924   ┆ 165      ┆ 21599          │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 21599          │
│ filter_3_microhomology_induced… ┆ 0.648178   ┆ 140      ┆ 21599          │
│ filter_4_highly_homologous_reg… ┆ 0.208343   ┆ 45       ┆ 21599          │
│ filter_5_soft_clipped_reads     ┆ 0.717626   ┆ 155      ┆ 21599          │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.00926    ┆ 2        ┆ 21599          │
│ filter_8_low_quality            ┆ 1.824159   ┆ 394      ┆ 21599          │
│ msec_filter_123                 ┆ 1.101903   ┆ 238      ┆ 21599          │
│ msec_filter_1234                ┆ 1.310246   ┆ 283      ┆ 21599          │
│ msec_filter_all                 ┆ 5.486365   ┆ 1185     ┆ 21599          │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [20]:
summarize_res(xml_arti_filter_1234)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 38.509317  ┆ 62       ┆ 161            │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 161            │
│ filter_3_microhomology_induced… ┆ 47.826087  ┆ 77       ┆ 161            │
│ filter_4_highly_homologous_reg… ┆ 27.950311  ┆ 45       ┆ 161            │
│ filter_5_soft_clipped_reads     ┆ 9.31677    ┆ 15       ┆ 161            │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.0        ┆ 0        ┆ 161            │
│ filter_8_low_quality            ┆ 3.10559    ┆ 5        ┆ 161            │
│ msec_filter_123                 ┆ 72.049689  ┆ 116      ┆ 161            │
│ msec_filter_1234                ┆ 100.0      ┆ 161      ┆ 161            │
│ msec_filter_all                 ┆ 100.0      ┆ 161      ┆ 161            │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [21]:
summarize_res(xml_arti_all_filter)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 7.345972   ┆ 62       ┆ 844            │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 844            │
│ filter_3_microhomology_induced… ┆ 9.123223   ┆ 77       ┆ 844            │
│ filter_4_highly_homologous_reg… ┆ 5.331754   ┆ 45       ┆ 844            │
│ filter_5_soft_clipped_reads     ┆ 14.810427  ┆ 125      ┆ 844            │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.236967   ┆ 2        ┆ 844            │
│ filter_8_low_quality            ┆ 44.78673   ┆ 378      ┆ 844            │
│ msec_filter_123                 ┆ 13.744076  ┆ 116      ┆ 844            │
│ msec_filter_1234                ┆ 19.075829  ┆ 161      ┆ 844            │
│ msec_filter_all                 ┆ 100.0      ┆ 844      ┆ 844            │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘